### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by jyotifun** [enzo-desimone/check_app_version#2]
two bugs:

1: fails to work on flutter desktop 
error : flutter: Failed host lookup: JSON URL site(any site is not ok)

2: update the readme example file

        onPressDecline: () {},
        onPressConfirm: () {},

these two properties does not exists

**Comment by enzo-desimone** [comment]
> two bugs:
> 
> 1: fails to work on flutter desktop error : flutter: Failed host lookup: JSON URL site(any site is not ok)
> 
> 2: update the readme example file
> 
> ```
>     onPressDecline: () {},
>     onPressConfirm: () {},
> ```
> 
> these two properties does not exists

In the plugin documentation, the two properties are present.

For the first error, did you start the example or did you make your own implementation? Could you post your implementation?
